# Generated by Django 5.2.1 on 2025-06-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
