# Generated by Django 5.2.1 on 2025-06-20 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_update', '0004_insuranceedit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_category', models.CharField(max_length=255)),
                ('code_type', models.CharField(max_length=100)),
                ('code_list', models.TextField(help_text='Comma-separated list of codes')),
                ('sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('modifier_instruction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_update.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
