# Generated by Django 5.2.1 on 2025-06-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_update', '0007_alter_user_role_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcategory_id', models.IntegerField()),
                ('dxcategory_code', models.CharField(max_length=100)),
                ('dxcategory_category', models.CharField(max_length=100)),
                ('dxcategory_sub_category', models.CharField(max_length=100)),
                ('dxcategory_type', models.CharField(max_length=100)),
                ('dxcategory_instructions', models.TextField()),
                ('dxcategory_sow_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.IntegerField()),
                ('scenario_code', models.CharField(max_length=100)),
                ('scenario_category', models.CharField(max_length=100)),
                ('scenario_sub_category', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(max_length=100)),
                ('scenario_instructions', models.TextField()),
                ('scenario_sow_id', models.CharField(max_length=100)),
            ],
        ),
    ]
